### ISSUE TITLE
Erro quando não há posicionamento existente

### ISSUE THREAD

**Issue by rafaelcoutinho** [pensandoodireito/sislegis-app#335]
Estou recebendo esse erro quando não há posicioamento existente:
TypeError: Cannot read property 'nome' of undefined
    at http://sislegis.local/scripts/services/ReuniaoFactory.js:22:108
    at Array.forEach (native)
    at $resource.buscarReuniaoPorData.transformResponse (http://sislegis.local/scripts/services/ReuniaoFactory.js:20:35)
    at sc (http://sislegis.local/lib/angular/angular.min.js:67:71)
    at c (http://sislegis.local/lib/angular/angular.min.js:68:297)
    at H (http://sislegis.local/lib/angular/angular.min.js:97:5)
    at http://sislegis.local/lib/angular/angular.min.js:98:173
    at h.$eval (http://sislegis.local/lib/angular/angular.min.js:108:40)

**Comment by rafaelcoutinho** [comment]
@marcoamarelo por favor veja quando queres fazer esse fix
